### ISSUE TITLE
new attribute on root level created

### ISSUE THREAD

**Issue by stoeren** [SwimStandardHub/lenex#16]
### What would you like to be added?

if there would be an attribute `created`, which is a datetime (format to be specified) 
Alternatitivly or additionally there could be a `revision` field added as an `integer` to represent a version of the file

### Why is this needed?

this would allow to track several versions of the same export and make sure the latest one is imported / this can be shown during an import process.

**Comment by PetzoldThomas** [comment]
> [!WARNING]
> The attribute `revision` maybe will be used for a revision number auf der standard

`created` is a good idea
